import {
  CAPABILITY_MODEL_STATUS_OPTIONS,
  CAPABILITY_ITEM_AI_ASSIST_MODE_OPTIONS,
  CAPABILITY_ITEM_EVIDENCE_TYPE_OPTIONS,
  CAPABILITY_ITEM_REVIEW_ROLE_OPTIONS,
  INDUSTRY_STATUS_OPTIONS,
  ROLE_STATUS_OPTIONS,
  createCapabilityModelDraft,
  createCapabilityModelVersion,
  createDefaultLevelScheme,
  createEmptyCapabilityDimension,
  createEmptyCapabilityItem,
  duplicateCapabilityModel,
  getCapabilityModel,
  getCapabilityModelStoreEventName,
  listCapabilityModels,
  listIndustries,
  listRoles,
  listSequences,
  publishCapabilityModel,
  removeCapabilityModel,
  removeIndustry,
  removeRole,
  removeSequence,
  saveCapabilityModel,
  saveIndustry,
  saveRole,
  saveSequence,
  seedCapabilityModelData,
  disableCapabilityModel,
} from './store';

export {
  CAPABILITY_MODEL_STATUS_OPTIONS,
  CAPABILITY_ITEM_AI_ASSIST_MODE_OPTIONS,
  CAPABILITY_ITEM_EVIDENCE_TYPE_OPTIONS,
  CAPABILITY_ITEM_REVIEW_ROLE_OPTIONS,
  INDUSTRY_STATUS_OPTIONS,
  ROLE_STATUS_OPTIONS,
  createCapabilityModelDraft,
  createCapabilityModelVersion,
  createDefaultLevelScheme,
  createEmptyCapabilityDimension,
  createEmptyCapabilityItem,
  getCapabilityModelStoreEventName,
};

export const capabilityModelApi = {
  seed: async () => seedCapabilityModelData(),
  listIndustries: async () => listIndustries(),
  saveIndustry: async (payload) => saveIndustry(payload),
  removeIndustry: async (id) => removeIndustry(id),
  listSequences: async () => listSequences(),
  saveSequence: async (payload) => saveSequence(payload),
  removeSequence: async (id) => removeSequence(id),
  listRoles: async () => listRoles(),
  saveRole: async (payload) => saveRole(payload),
  removeRole: async (id) => removeRole(id),
  listModels: async () => listCapabilityModels(),
  detailModel: async (id) => getCapabilityModel(id),
  saveModel: async (payload) => saveCapabilityModel(payload),
  duplicateModel: async (id) => duplicateCapabilityModel(id),
  createVersion: async (id) => createCapabilityModelVersion(id),
  publishModel: async (id) => publishCapabilityModel(id),
  disableModel: async (id) => disableCapabilityModel(id),
  removeModel: async (id) => removeCapabilityModel(id),
};
