export const SOLUTION_SHOWROOM_ROOMS = [
  {
    id: 'tongda-ai-literacy-teaching',
    solutionName: '通答：（人工智能通识）教学平台',
    solutionCode: 'SHOWROOM-AI-LITERACY',
    tenantId: 'tenant-ai-literacy-teaching',
    tenantName: '人工智能通识教学样板租户',
    tenantCode: 'TENANT-AI-LITERACY',
    tenantType: '教学平台',
    region: '全国',
    industry: '人工智能通识教育',
    packageId: 'pkg-pro',
    packageName: '专业版套餐',
    packageCode: 'PKG-PRO',
    stage: '教学样板',
    scenario: '教学空间',
    owner: '教研中心',
    accent: '#2563eb',
    tone: 'blue',
    description: '面向人工智能通识课程建设，展示课程空间、资源沉淀、AI 助教和学习过程运营的一体化租户页面。',
    signal: '人工智能通识教学样板',
    domain: 'ai-literacy.demo.guoren.ai',
    modules: ['课程空间', '资料库', 'Lucky 助教', '作业任务', '学习评价', '证书'],
    metrics: [
      { label: '课程单元', value: '32' },
      { label: '学习空间', value: '18' },
      { label: '资源素材', value: '1,260' },
    ],
    tenantKpis: [
      { label: '课程单元', value: '32', trend: '已配置' },
      { label: 'AI 助教问答', value: '8.6k', trend: '+24%' },
      { label: '学习任务完成', value: '87%', trend: '+9%' },
      { label: '教学资源', value: '1,260', trend: '+138' },
    ],
    workflow: ['课程建模', '资源导入', '空间开课', 'AI 助学', '任务评价', '成果归档'],
    operations: [
      { label: '待发布课程', value: '6 个' },
      { label: '待批改任务', value: '42 份' },
      { label: '本周活跃空间', value: '15 个' },
    ],
    loginConfig: {
      platformName: '通答人工智能通识教学平台',
      heroTitle: 'AI通识教学',
      heroSubtitle: '课程、资源、助教与评价一体化',
      accentColor: '#2563eb',
    },
  },
  {
    id: 'tongda-agent-platform',
    solutionName: '通答：智能体平台',
    solutionCode: 'SHOWROOM-AGENT',
    tenantId: 'tenant-agent-platform',
    tenantName: '智能体平台样板租户',
    tenantCode: 'TENANT-AGENT',
    tenantType: '智能体平台',
    region: '全国',
    industry: 'AI 智能体',
    packageId: 'pkg-ultimate',
    packageName: '旗舰版套餐',
    packageCode: 'PKG-ULTIMATE',
    stage: '智能体样板',
    scenario: '综合解决方案',
    owner: 'AI 产品中心',
    accent: '#7c3aed',
    tone: 'violet',
    description: '展示智能体创建、技能编排、知识检索、调用监控和组织级权限管理的租户页面。',
    signal: '智能体能力运营样板',
    domain: 'agent.demo.guoren.ai',
    modules: ['智能体', '技能库', '知识库', '调用统计', '权限管理', '消息触达'],
    metrics: [
      { label: '智能体', value: '48' },
      { label: '技能', value: '126' },
      { label: '月调用', value: '320k' },
    ],
    tenantKpis: [
      { label: '在线智能体', value: '48', trend: '+8' },
      { label: '技能编排', value: '126', trend: '+21' },
      { label: '知识命中率', value: '91%', trend: '+6%' },
      { label: '月调用量', value: '320k', trend: '+18%' },
    ],
    workflow: ['需求登记', '技能配置', '知识绑定', '智能体发布', '调用监控', '持续优化'],
    operations: [
      { label: '待审核智能体', value: '7 个' },
      { label: '高频技能', value: '资料综述' },
      { label: '异常调用', value: '3 条' },
    ],
    loginConfig: {
      platformName: '通答智能体平台',
      heroTitle: '智能体协作',
      heroSubtitle: '搭建、发布和运营组织级 AI 智能体',
      accentColor: '#7c3aed',
    },
  },
  {
    id: 'k12-service-platform',
    solutionName: '中小学服务平台',
    solutionCode: 'SHOWROOM-K12-SERVICE',
    tenantId: 'tenant-k12-service',
    tenantName: '中小学服务样板租户',
    tenantCode: 'TENANT-K12-SERVICE',
    tenantType: '服务平台',
    region: '全国',
    industry: '基础教育',
    packageId: 'pkg-pro',
    packageName: '专业版套餐',
    packageCode: 'PKG-PRO',
    stage: '服务样板',
    scenario: '综合解决方案',
    owner: '基础教育事业部',
    accent: '#0f766e',
    tone: 'teal',
    description: '面向中小学日常服务场景，展示组织、资源、通知、任务、活动和数据看板的一体化租户页面。',
    signal: '中小学综合服务样板',
    domain: 'k12-service.demo.guoren.ai',
    modules: ['组织管理', '空间', '资料库', '消息', '任务', '活动'],
    metrics: [
      { label: '服务事项', value: '64' },
      { label: '覆盖班级', value: '128' },
      { label: '通知触达', value: '96%' },
    ],
    tenantKpis: [
      { label: '服务事项', value: '64', trend: '运行中' },
      { label: '班级空间', value: '128', trend: '+12' },
      { label: '通知触达', value: '96%', trend: '+3%' },
      { label: '待办处理', value: '89%', trend: '+6%' },
    ],
    workflow: ['组织初始化', '事项配置', '空间开通', '通知下发', '任务跟进', '数据复盘'],
    operations: [
      { label: '待处理事项', value: '18 项' },
      { label: '本周活动', value: '12 场' },
      { label: '异常提醒', value: '5 条' },
    ],
    loginConfig: {
      platformName: '中小学服务平台',
      heroTitle: '学校服务中台',
      heroSubtitle: '连接组织、事项、通知与数据',
      accentColor: '#0f766e',
    },
  },
  {
    id: 'teacher-development-platform',
    solutionName: '教师发展平台',
    solutionCode: 'SHOWROOM-TEACHER-DEVELOPMENT',
    tenantId: 'tenant-teacher-development',
    tenantName: '教师发展样板租户',
    tenantCode: 'TENANT-TEACHER-DEVELOPMENT',
    tenantType: '发展平台',
    region: '全国',
    industry: '教师发展',
    packageId: 'pkg-ultimate',
    packageName: '旗舰版套餐',
    packageCode: 'PKG-ULTIMATE',
    stage: '发展样板',
    scenario: '组织培训',
    owner: '教师发展中心',
    accent: '#f97316',
    tone: 'orange',
    description: '展示教师画像、能力模型、研修项目、评价反馈和成长档案联动的租户页面。',
    signal: '教师专业成长样板',
    domain: 'teacher-dev.demo.guoren.ai',
    modules: ['教师画像', '能力模型', '研修空间', '评价方案', '资料库', '证书'],
    metrics: [
      { label: '教师画像', value: '2,480' },
      { label: '研修项目', value: '36' },
      { label: '成长记录', value: '18k' },
    ],
    tenantKpis: [
      { label: '教师画像', value: '2,480', trend: '+320' },
      { label: '能力达标', value: '78%', trend: '+8%' },
      { label: '研修项目', value: '36', trend: '进行中' },
      { label: '成果档案', value: '18k', trend: '+1.2k' },
    ],
    workflow: ['画像建档', '能力诊断', '项目报名', '研修任务', '评价反馈', '成长归档'],
    operations: [
      { label: '待评价教师', value: '86 人' },
      { label: '活跃研修项目', value: '14 个' },
      { label: '待归档成果', value: '238 份' },
    ],
    loginConfig: {
      platformName: '教师发展平台',
      heroTitle: '教师成长',
      heroSubtitle: '画像、研修、评价与档案一体化',
      accentColor: '#f97316',
    },
  },
  {
    id: 'smart-continuing-education',
    solutionName: '智慧继教',
    solutionCode: 'SHOWROOM-CONTINUING-EDU',
    tenantId: 'tenant-continuing-edu',
    tenantName: '智慧继教样板租户',
    tenantCode: 'TENANT-CONTINUING-EDU',
    tenantType: '继续教育',
    region: '全国',
    industry: '继续教育',
    packageId: 'pkg-standard',
    packageName: '标准版套餐',
    packageCode: 'PKG-STANDARD',
    stage: '继教样板',
    scenario: '组织培训',
    owner: '继教运营中心',
    accent: '#0891b2',
    tone: 'cyan',
    description: '展示继续教育项目发布、报名学习、学时管理、过程监督和证书发放的租户页面。',
    signal: '继续教育运营样板',
    domain: 'continuing-edu.demo.guoren.ai',
    modules: ['项目管理', '学习空间', '学时统计', '问卷', '证书', '消息'],
    metrics: [
      { label: '继教项目', value: '28' },
      { label: '报名学员', value: '6,200' },
      { label: '学时完成', value: '84%' },
    ],
    tenantKpis: [
      { label: '继教项目', value: '28', trend: '本期' },
      { label: '报名学员', value: '6,200', trend: '+860' },
      { label: '学时完成', value: '84%', trend: '+11%' },
      { label: '证书发放', value: '4,860', trend: '+520' },
    ],
    workflow: ['项目发布', '报名审核', '课程学习', '学时核验', '反馈问卷', '证书发放'],
    operations: [
      { label: '待审核报名', value: '126 人' },
      { label: '待核验学时', value: '340 条' },
      { label: '即将截止项目', value: '5 个' },
    ],
    loginConfig: {
      platformName: '智慧继教平台',
      heroTitle: '智慧继教',
      heroSubtitle: '项目、学时、证书与运营闭环',
      accentColor: '#0891b2',
    },
  },
  {
    id: 'teacher-portfolio-platform',
    solutionName: '教师（/教学）档案袋',
    solutionCode: 'SHOWROOM-TEACHER-PORTFOLIO',
    tenantId: 'tenant-teacher-portfolio',
    tenantName: '教师档案袋样板租户',
    tenantCode: 'TENANT-TEACHER-PORTFOLIO',
    tenantType: '档案平台',
    region: '全国',
    industry: '教师档案',
    packageId: 'pkg-standard',
    packageName: '标准版套餐',
    packageCode: 'PKG-STANDARD',
    stage: '档案样板',
    scenario: '综合解决方案',
    owner: '档案运营中心',
    accent: '#4f46e5',
    tone: 'indigo',
    description: '展示教师教学成果、评价证据、培训记录、证书材料和成长轨迹沉淀的档案袋租户页面。',
    signal: '教师教学档案样板',
    domain: 'teacher-portfolio.demo.guoren.ai',
    modules: ['我的档案', '资料库', '评价证据', '证书', '成长记录', '权限共享'],
    metrics: [
      { label: '档案数量', value: '3,820' },
      { label: '证据材料', value: '24k' },
      { label: '共享申请', value: '168' },
    ],
    tenantKpis: [
      { label: '档案数量', value: '3,820', trend: '+418' },
      { label: '证据材料', value: '24k', trend: '+2.1k' },
      { label: '待审核材料', value: '312', trend: '待处理' },
      { label: '共享申请', value: '168', trend: '+24' },
    ],
    workflow: ['档案建模', '材料采集', '证据标注', '审核入袋', '授权共享', '成长复盘'],
    operations: [
      { label: '待审核材料', value: '312 份' },
      { label: '本周新增档案', value: '148 份' },
      { label: '共享申请', value: '168 条' },
    ],
    loginConfig: {
      platformName: '教师教学档案袋',
      heroTitle: '档案袋',
      heroSubtitle: '沉淀教师成长与教学证据',
      accentColor: '#4f46e5',
    },
  },
];

export function getSolutionShowroomRoom(roomId) {
  return SOLUTION_SHOWROOM_ROOMS.find((item) => item.id === roomId) || null;
}

export const GUOREN_INTERNAL_PORTAL_ENTRY = {
  id: 'guoren-exchange',
  solutionName: '果仁交流',
  solutionCode: 'INTERNAL-GUOREN-EXCHANGE',
  tenantId: 'tenant-guoren-exchange',
  tenantName: '果仁交流内部运营租户',
  tenantCode: 'TENANT-GUOREN-EXCHANGE',
  tenantType: '内部运营',
  region: '北京',
  industry: '公司内部运营',
  packageId: 'pkg-pro',
  packageName: '专业版套餐',
  packageCode: 'PKG-PRO',
  stage: '内部运营租户',
  scenario: '社区运营',
  owner: '果仁运营团队',
  accent: '#0f766e',
  tone: 'internal',
  entryType: 'internal',
  description: '用于公司内部果仁平台的交流、运营、内容发布和成员协作，不归入对外样板间。',
  signal: '公司内部果仁平台运营入口',
  domain: 'guoren-exchange.internal.guoren.ai',
  modules: ['交流空间', '内容发布', '成员运营', '任务协同', '消息通知', '资料沉淀'],
  metrics: [
    { label: '运营栏目', value: '12' },
    { label: '内部成员', value: '86' },
    { label: '本周互动', value: '428' },
  ],
  tenantKpis: [
    { label: '运营栏目', value: '12', trend: '内部' },
    { label: '内部成员', value: '86', trend: '+6' },
    { label: '本周互动', value: '428', trend: '+18%' },
    { label: '待处理任务', value: '19', trend: '进行中' },
  ],
  workflow: ['栏目配置', '内容发布', '成员互动', '任务协同', '运营复盘', '资料沉淀'],
  operations: [
    { label: '待发布内容', value: '8 篇' },
    { label: '待跟进讨论', value: '14 条' },
    { label: '本周运营任务', value: '19 项' },
  ],
  loginConfig: {
    platformName: '果仁交流',
    heroTitle: '内部交流运营',
    heroSubtitle: '面向公司内部的果仁平台运营入口',
    accentColor: '#0f766e',
  },
};
