import {
  buildSceneInitialVersionData,
  createTemplateDraft,
  duplicateSceneTemplate,
  getScene,
  getSceneMenuLabel,
  getSceneStoreChangeEventName,
  getSceneTemplate,
  listSceneSystemMenuShortcuts,
  listSceneTemplates,
  listScenes,
  removeScene,
  removeSceneTemplate,
  saveScene,
  saveSceneTemplate,
  seedSceneData,
  toggleSceneMenuShortcut,
  toggleSceneSystemMenuShortcut,
} from './store';

export const sceneApi = {
  seed: async () => seedSceneData(),
  listTemplates: async () => listSceneTemplates(),
  listSceneSystemMenuShortcuts: async () => listSceneSystemMenuShortcuts(),
  detailTemplate: async (id) => getSceneTemplate(id),
  saveTemplate: async (template) => saveSceneTemplate(template),
  removeTemplate: async (id) => removeSceneTemplate(id),
  duplicateTemplate: async (id) => duplicateSceneTemplate(id),
  listScenes: async () => listScenes(),
  detailScene: async (id) => getScene(id),
  saveScene: async (scene) => saveScene(scene),
  toggleSceneMenuShortcut: async (id, enabled) => toggleSceneMenuShortcut(id, enabled),
  toggleSceneSystemMenuShortcut: async (menuKey, enabled) => toggleSceneSystemMenuShortcut(menuKey, enabled),
  removeScene: async (id) => removeScene(id),
  createTemplateDraft,
  buildSceneInitialVersionData,
  getSceneMenuLabel,
  getStoreEventName: getSceneStoreChangeEventName,
};

export * from './store';
